config/routes.rb
Rails.application.routes.draw do
 get '/posts/mypage', to: "posts#mypage"
 post '/posts/:post_id' =>"comments#create"
delete '/posts/:post_id/comments/:id' =>"comments#destroy"
 root 'posts#index'
  get 'comments/create'
  get 'comments/destroy'
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image
  belongs_to :user
has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :posts
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    @comment.comment = params[:comment]
    @comment.user_id = params[:user_id]
    @comment.save
    
    redirect_to @post

end

def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    
    redirect_to @post
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

def mypage
@myposts = Post.all.order("created_at DESC")
end


  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

  <title>UISEOP</title>
<!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

</head>

  <body>
<nav class="navbar navbar-inverse">

  <div class="container">

    <div class="navbar-header">

      <a class="navbar-brand" href="/">Dongguk News</a>

    </div>

    <ul class="nav navbar-nav">

      <li class="active"><a href="/">메인 화면</a></li>

    </ul>

    <ul class="nav navbar-nav navbar-right">

   

      <% if user_signed_in? %>

   <a href="/posts/new" style="float: left; margin-right: 50px;" class="btn btn-success navbar-btn"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;글작성 하기</a> <li><a href="#"><strong><%= current_user.email %></strong>님 환영합니다.</a></li><li><a href="/posts/mypage"><span class="glyphicon glyphicon-home"></strong> 내페이지</a></li><li><a href="/users/sign_out"><span class="glyphicon glyphicon-log-out"></span> 로그아웃</a></li> 

      <% else %>

        <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> 회원 가입</a></li>

        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> 로그인</a></li>

      <% end %>

    </ul>

  </div>

</nav>

<div class="container">

  <%= yield %>

</div>



</body>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
  <div class="form-group row">
    <%= form.label :제목 %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :내용 %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

<div class="form-group row">
    <%= form.label :image %><br>
    <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
</div>

<div class="field">
  <%= form.hidden_field :user_id , :value => current_user.id %>
</div>

</div>

  <div class="actions">
 <%= form.submit"글쓰기",class:"btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>수정하기</h1>

<%= render 'form', post: @post %>

<%= link_to '뒤로가기', @post %> |
<%= link_to '게시글보기', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>게시판</h1>

    <div class="jumbotron">

      <div class="container">

        <table class="table table-striped">
  <thead>
    <tr>
      <th>제목</th>
      <th>작성자</th>
      <th>작성된 시간</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
       <td><%= link_to post.title, post %></td>
        <td><%= post.user.email %></td>
        <td><%= post.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
      </div>
    </div>

<br>

app/views/posts/mypage.html.erb
<p id="notice"><%= notice %></p>

<h1>내 페이지</h1>

    <div class="jumbotron">

      <div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th>내가 작성한 글 목록</th>
     <th>작성자</th>
      <th>작성된 시간</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
  
   <% @myposts.each do |post| %>
   <% if current_user.email == post.user.email %>
<tr>
       <td><%= link_to post.title, post %></td><br>
        <td><%= post.user.email %></td>
        <td><%= post.created_at %></td>
</tr>

<% end %>
<% end %>
  </tbody>
</table>
<br>
      </div>
    </div>

<a href="/">뒤로가기</a>

app/views/posts/new.html.erb
<h1>게시물 작성</h1>

<%= render 'form', post: @post %>

<%= link_to '돌아가기', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <h2><%= @post.title %></h2>
  <hr>

  <p><strong>작성자</strong></p>
  <p><%= @post.user.email %></p>
  <hr>


  <p><strong>내용</strong></p>
  <p><%= @post.content %></p>
  <hr>

<p>
    <strong>사진:</strong>
    <%= image_tag("#{@post.image}") %>
</p>

<hr>
<p><strong>댓글작성</strong></p>
 <div class="well">
  <form action="/posts/<%=@post.id%>" method="post">
   <div class="form-group">
<% if user_signed_in? %>
    <input type="hidden" value="<%=current_user.id%>" name="user_id"></input>
    <input type="hidden" value="<%=@post.id%>" name="post_id"></input>
    <textarea class="form-control" rows="5" name="comment"></textarea>
   </div>
   <button type="submit" class="btn btn-default">댓글작성!</button>
<% else %>
<% end %>
  </form>
 </div>
<hr>
<p><strong>댓글목록</strong></p>
<% @comments = @post.comments.all.reverse %>
<% @comments.each do |c| %>
 <div class="well">
  <p>작성자 : <%= c.user.email %></p>
  <p>내용 : <%= c.comment %></p>
<% if user_signed_in? %>
   <% if current_user.email == c.user.email %>
<a href="/posts/<%=@post.id%>/comments/<%=c.id%>" data-method="delete" class="btn btn-primary">댓글삭제</a>
   <% end %>
<% end %>
 </div>
<% end %>

<% if user_signed_in? %>
<% if current_user.email == @post.user.email %>
<%= link_to '수정하기', edit_post_path(@post) %> |
  <%= link_to '돌아가기', posts_path %> |
  <%= link_to '삭제하기', @post, method: :delete, data: { confirm: '게시물을 삭제하시겠습니까?' } %>
<% else %>
 <%= link_to '돌아가기', posts_path %>
<% end %>
<% else %>
  <%= link_to '돌아가기', posts_path %>
<% end %>